name = input("Enter your name: ")
age = int(input("Enter your age: "))
branch = input("Enter your branch: ")
college = input("Enter your college: ")
cgpa = float(input("Enter your CGPA: "))
dream_job = input("Enter your dream job: ")
print("\n========== STUDENT INFORMATION ==========")
print("Name      :", name)
print("Age       :", age)
print("Branch    :", branch)
print("College   :", college)
print("CGPA      :", cgpa)
print("Dream Job :", dream_job)
print("=========================================")
